# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff2f769af4f1887d83f850c51117c3fc0443b5795b9c3d7b04ec265ad04fefdf74ec777af124d9ac6929febf82a53d0d34198259baff532ea88dc99f4c32536c

test:
  secret_key_base: 07666e60eb7083de78ef7eb98b4f4dc01c885774be4f36e81ce235553912badcf2a8beca2eb2e14f236b41118c4f63386ad6e9a47b764a79e4b9d83e03f1c641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
